on:
  push:
  pull_request:

name: Build

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Setup pnpm, Node.js, and dependencies
        uses: pnpm/setup@v2.1.0
        with:
          cache: true
          require-lockfile: true

      - name: Build the project
        run: pnpm -r build
