name: Changesets

on:
  push:
    branches:
      - main

env:
  CI: true

permissions:
  contents: write
  pull-requests: write

jobs:
  version:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: checkout code repository
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: setup pnpm, node.js, and dependencies
        uses: pnpm/setup@v2.1.0
        with:
          cache: true
          require-lockfile: true

      - name: configure npm authentication
        run: pnpm config set //registry.npmjs.org/:_authToken '${NODE_AUTH_TOKEN}'

      - name: build project
        run: pnpm -r build

      - name: create and publish versions
        uses: changesets/action@v2
        with:
          version-script: pnpm ci:version
          commit-message: "chore: update versions"
          pr-title: "chore: update versions"
          publish-script: pnpm ci:publish
          create-github-releases: true
