name: Publish Package to npmjs
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 8
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: pnpm
      - name: Install dependencies
        run: pnpm install
      - name: Build the project
        run: pnpm -r build
      - name: Publish the project
        run: pnpm -r publish
      # Get version in package.json and tag it
      - name: Get version
        id: get_version
        run: echo ::set-output name=version::$(node -p "require('./package.json').version")
